export const OPEN_COMPARE_LIST = 'OPEN_COMPARE_LIST';
export const ADD_PRODUCT_TO_COMPARE = 'ADD_PRODUCT_TO_COMPARE';
export const REMOVE_PRODUCT_FROM_COMPARE = 'REMOVE_PRODUCT_FROM_COMPARE';
export const CLEAR_COMPARE = 'CLEAR_COMPARE';
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
